# Generated by Django 5.1.6 on 2025-02-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('furniture_type', models.CharField(choices=[('oshxona', 'Oshxona mebeli'), ('yotoqxona', 'Yotoqxona mebeli'), ('bolalar', 'Bolalar mebeli'), ('yumshoq', 'Yumshoq mebellar'), ('shkaf', 'Shkaf va gardirob'), ('eshik', 'Eshiklar')], max_length=20)),
            ],
        ),
    ]
